/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author lintv_000
 */
public class DPcalcGUIFrame extends javax.swing.JFrame {

   // public String image = "C:\\Users\\lintv_000\\Desktop\\Project\\C_ITOO121Project\\Emojis\\nutral.jpg"; 
    /**
     * Creates new form DPcalcGUIFrame
     */
    public DPcalcGUIFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcPnl = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        semMarkLbl = new javax.swing.JLabel();
        contassmarkLbl = new javax.swing.JLabel();
        assMarkLbl = new javax.swing.JLabel();
        SemTestWeightLbl = new javax.swing.JLabel();
        ContAssWeightLbl = new javax.swing.JLabel();
        AssWeightLbl = new javax.swing.JLabel();
        HelpLbl = new javax.swing.JLabel();
        PercentageLbl = new javax.swing.JLabel();
        emoticon = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox();
        SenesterMarkTextBox = new javax.swing.JTextField();
        ContiniousAsessmentMarkTextBox = new javax.swing.JTextField();
        AssignmentMarkTextBox = new javax.swing.JTextField();
        SemTestWeightTextBox = new javax.swing.JTextField();
        ContAssWeightTextBox = new javax.swing.JTextField();
        AssWeightTextBox = new javax.swing.JTextField();
        calculatebtn = new javax.swing.JButton();
        AddSubjectBtn = new javax.swing.JButton();
        ResteBtn = new javax.swing.JButton();
        HelpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dp Calculater By Jaco Lintvelt");

        headingLbl.setFont(new java.awt.Font("Batang", 0, 11)); // NOI18N
        headingLbl.setText("Dp Calculator");

        semMarkLbl.setText("Semester Test Mark");

        contassmarkLbl.setText("Continious assesment mark");

        assMarkLbl.setText("Assignment Mark");

        SemTestWeightLbl.setText("Semester Test weight ");

        ContAssWeightLbl.setText("Continious assesment weight");

        AssWeightLbl.setText("Assignment Weight");

        HelpLbl.setText("Press calculate to calculate dp");

        PercentageLbl.setText("Persentage ");

        emoticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\lintv_000\\Desktop\\Project\\C_ITOO121Project\\Emojis\\nutral.jpg")); // NOI18N

        subjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Object Orientated Programming", "Network Technology", "Software Development", "Human Computer Interaction", "Introduction to information Systems", "Computer Skills", " " }));
        subjectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboBoxActionPerformed(evt);
            }
        });

        SenesterMarkTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenesterMarkTextBoxActionPerformed(evt);
            }
        });

        SemTestWeightTextBox.setText("0.2");

        ContAssWeightTextBox.setText("0.2");

        AssWeightTextBox.setText("0.6");

        calculatebtn.setText("Calculate");
        calculatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebtnActionPerformed(evt);
            }
        });

        AddSubjectBtn.setText("Add subject");

        ResteBtn.setText("Reset");
        ResteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResteBtnActionPerformed(evt);
            }
        });

        HelpBtn.setText("Help");

        javax.swing.GroupLayout calcPnlLayout = new javax.swing.GroupLayout(calcPnl);
        calcPnl.setLayout(calcPnlLayout);
        calcPnlLayout.setHorizontalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contassmarkLbl)
                    .addComponent(semMarkLbl)
                    .addComponent(assMarkLbl)
                    .addComponent(SemTestWeightLbl)
                    .addComponent(ContAssWeightLbl)
                    .addComponent(AssWeightLbl))
                .addGap(169, 169, 169)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingLbl)
                    .addComponent(PercentageLbl)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AssWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ContAssWeightTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(SemTestWeightTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AssignmentMarkTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContiniousAsessmentMarkTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenesterMarkTextBox, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPnlLayout.createSequentialGroup()
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddSubjectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HelpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPnlLayout.createSequentialGroup()
                        .addComponent(HelpLbl)
                        .addGap(63, 63, 63))))
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(emoticon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcPnlLayout.setVerticalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addComponent(headingLbl)
                        .addGap(18, 18, 18)
                        .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(semMarkLbl)
                        .addGap(18, 18, 18)
                        .addComponent(contassmarkLbl))
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addComponent(SenesterMarkTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContiniousAsessmentMarkTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assMarkLbl)
                    .addComponent(AssignmentMarkTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemTestWeightLbl)
                    .addComponent(SemTestWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContAssWeightLbl)
                    .addComponent(ContAssWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssWeightTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssWeightLbl))
                        .addGap(27, 47, Short.MAX_VALUE))
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HelpLbl)
                        .addGap(18, 18, 18)
                        .addComponent(calculatebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PercentageLbl)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addComponent(AddSubjectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HelpBtn)))
                .addGap(26, 26, 26)
                .addComponent(emoticon)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenesterMarkTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenesterMarkTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenesterMarkTextBoxActionPerformed

    private void subjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectComboBoxActionPerformed

    private void calculatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebtnActionPerformed

        try {
            Double assignmentMark = Double.parseDouble(AssignmentMarkTextBox.getText());
            Double semesterTest = Double.parseDouble(SenesterMarkTextBox.getText());
            Double contAss = Double.parseDouble(ContiniousAsessmentMarkTextBox.getText());
            Double AssWeight = Double.parseDouble(AssWeightTextBox.getText());
            Double ContAssWeight = Double.parseDouble(ContAssWeightTextBox.getText());
            Double SemTestWeight = Double.parseDouble(SemTestWeightTextBox.getText());
            
            DPcalc dp = new DPcalc( assignmentMark, semesterTest,contAss ,null,null,null,AssWeight,ContAssWeight,SemTestWeight );
          
            PercentageLbl.setText(dp.calculateDP() + " %");
            
            if (dp.canWriteExams())
        {
            emoticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\lintv_000\\Desktop\\Project\\C_ITOO121Project\\Emojis\\Happy.jpg"));
        }
            
        else
        {
           emoticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\lintv_000\\Desktop\\Project\\C_ITOO121Project\\Emojis\\Sad.jpg"));
           
        }} catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(rootPane, "Make sure to enter a valad number");
        }
        
        
        
    }//GEN-LAST:event_calculatebtnActionPerformed

    private void ResteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResteBtnActionPerformed
        AssignmentMarkTextBox.setText("");
        SenesterMarkTextBox.setText("");
        ContiniousAsessmentMarkTextBox.setText("");
         emoticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\lintv_000\\Desktop\\Project\\C_ITOO121Project\\Emojis\\nutral.jpg"));
    }//GEN-LAST:event_ResteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPcalcGUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSubjectBtn;
    private javax.swing.JLabel AssWeightLbl;
    private javax.swing.JTextField AssWeightTextBox;
    private javax.swing.JTextField AssignmentMarkTextBox;
    private javax.swing.JLabel ContAssWeightLbl;
    private javax.swing.JTextField ContAssWeightTextBox;
    private javax.swing.JTextField ContiniousAsessmentMarkTextBox;
    private javax.swing.JButton HelpBtn;
    private javax.swing.JLabel HelpLbl;
    private javax.swing.JLabel PercentageLbl;
    private javax.swing.JButton ResteBtn;
    private javax.swing.JLabel SemTestWeightLbl;
    private javax.swing.JTextField SemTestWeightTextBox;
    private javax.swing.JTextField SenesterMarkTextBox;
    private javax.swing.JLabel assMarkLbl;
    private javax.swing.JPanel calcPnl;
    private javax.swing.JButton calculatebtn;
    private javax.swing.JLabel contassmarkLbl;
    private javax.swing.JLabel emoticon;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel semMarkLbl;
    private javax.swing.JComboBox subjectComboBox;
    // End of variables declaration//GEN-END:variables
}
