/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

import java.io.File;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ras
 */
public class DPcalcGUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form calcFrame
     */
    public DPcalcGUIFrame() {
        initComponents();
        this.setVisible (true);
        
        
    } 
    
    ImageIcon frownEmoti = new ImageIcon("src\\main\\resources\\Frowny face.PNG", "a pretty but meaningless splat");
    ImageIcon neutralEmoti = new ImageIcon("src\\main\\resources\\Neutral face.PNG", "a pretty but meaningless splat");
    ImageIcon smileyEmoti = new ImageIcon("src\\main\\resources\\Smiley face.PNG", "a pretty but meaningless splat");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcPnl = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        subjectsCmboBox = new javax.swing.JComboBox();
        semTestMarkLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        assignMentMarkLbl = new javax.swing.JLabel();
        semesterTestWeightLbl = new javax.swing.JLabel();
        contAssesmentWeightLbl = new javax.swing.JLabel();
        assignmentWeightLbl = new javax.swing.JLabel();
        semTestMarkTxtField = new javax.swing.JTextField();
        contAssesTxtField = new javax.swing.JTextField();
        assignmentMarkTxtField = new javax.swing.JTextField();
        semWeightTxtField = new javax.swing.JTextField();
        contWeightTxtField = new javax.swing.JTextField();
        assWeightTxtField = new javax.swing.JTextField();
        passOrFailLbl = new javax.swing.JLabel();
        percentageLbl = new javax.swing.JLabel();
        multiSubjectBtn = new javax.swing.JButton();
        calculateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        emoticon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DP Calculator - by Ras Brits");

        headingLbl.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        headingLbl.setText("-DP calculator-");

        subjectsCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Subject>", "Object Oriented Programming", "Computer Skills", "Networking Technologies", "Human computer Interaction", "Software development project" }));

        semTestMarkLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        semTestMarkLbl.setText("Sem Test Mark");

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        jLabel3.setText("Cont asses mark");

        assignMentMarkLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        assignMentMarkLbl.setText("Assignment mark");

        semesterTestWeightLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        semesterTestWeightLbl.setText("Sem test weight");

        contAssesmentWeightLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        contAssesmentWeightLbl.setText("Cont weight");

        assignmentWeightLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        assignmentWeightLbl.setText("Ass weight");

        semWeightTxtField.setText("0.2");

        contWeightTxtField.setText("0.2");

        assWeightTxtField.setText("0.6");

        passOrFailLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        passOrFailLbl.setText("Pass/Fail");

        percentageLbl.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        percentageLbl.setText("percentage");

        multiSubjectBtn.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        multiSubjectBtn.setText("Multi subject");
        multiSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiSubjectBtnActionPerformed(evt);
            }
        });

        calculateBtn.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        helpBtn.setFont(new java.awt.Font("Trajan Pro", 0, 13)); // NOI18N
        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        emoticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Neutral face.PNG"))); // NOI18N

        javax.swing.GroupLayout calcPnlLayout = new javax.swing.GroupLayout(calcPnl);
        calcPnl.setLayout(calcPnlLayout);
        calcPnlLayout.setHorizontalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addComponent(headingLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectsCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passOrFailLbl)
                            .addGroup(calcPnlLayout.createSequentialGroup()
                                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semTestMarkLbl)
                                    .addComponent(jLabel3)
                                    .addComponent(assignMentMarkLbl)
                                    .addComponent(semesterTestWeightLbl)
                                    .addComponent(contAssesmentWeightLbl)
                                    .addComponent(assignmentWeightLbl)
                                    .addGroup(calcPnlLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(emoticon))
                                    .addComponent(percentageLbl))
                                .addGap(38, 38, 38)
                                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(calcPnlLayout.createSequentialGroup()
                                        .addComponent(resetBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(helpBtn))
                                    .addComponent(multiSubjectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(assWeightTxtField)
                                    .addComponent(contWeightTxtField)
                                    .addComponent(semWeightTxtField)
                                    .addComponent(assignmentMarkTxtField)
                                    .addComponent(contAssesTxtField)
                                    .addComponent(semTestMarkTxtField)
                                    .addComponent(calculateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        calcPnlLayout.setVerticalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addComponent(headingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectsCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semTestMarkLbl)
                    .addComponent(semTestMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contAssesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignMentMarkLbl)
                    .addComponent(assignmentMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterTestWeightLbl)
                    .addComponent(semWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contAssesmentWeightLbl)
                    .addComponent(contWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentWeightLbl)
                    .addComponent(assWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passOrFailLbl)
                .addGap(16, 16, 16)
                .addComponent(percentageLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multiSubjectBtn)
                        .addGap(18, 18, 18)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn)
                            .addComponent(helpBtn)))
                    .addComponent(emoticon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calcPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
       
        String name = "";
        String dv = "";
        String subject = subjectsCmboBox.getSelectedItem().toString ();
                
       DPcalc calc = new DPcalc (Double.parseDouble(assignmentMarkTxtField.getText ()),Double.parseDouble(semTestMarkTxtField.getText ()),Double.parseDouble(contAssesTxtField.getText ()),name, dv , subject, Double.parseDouble(assWeightTxtField.getText ()),Double.parseDouble(semWeightTxtField.getText ()),Double.parseDouble(contWeightTxtField.getText ()) );
       calc.setAssignmentWeight(Double.parseDouble (semWeightTxtField.getText ()));
       calc.setContinuousAssessmentWeight(Double.parseDouble (contWeightTxtField.getText ()));
       calc.setSemesterTestWeight(Double.parseDouble (semWeightTxtField.getText ()));
       
       //Check if the person can write exams
       if (calc.canWriteExams() == true)
       {
           passOrFailLbl.setText("Pass");
           emoticon.setIcon(smileyEmoti);
       }
       else
       {
           passOrFailLbl.setText("Fail");
           emoticon.setIcon(frownEmoti);

       }
       checkPercentages ();
        //This will round to two deciamls 
        DecimalFormat df = new DecimalFormat("#.##");
        
        //Limit percentage output to 100
        if(calc.calculateDP() > 100)
        {
            percentageLbl.setText ("Percertage : " + "100");
        }
        else
        {
            percentageLbl.setText ("Percertage : " + df.format(calc.calculateDP()));
        }
       
       
    }//GEN-LAST:event_calculateBtnActionPerformed

    void checkPercentages ()
    {
        //This method checks the weights
        Double perc1 = Double.parseDouble (semWeightTxtField.getText ());
        Double perc2 = Double.parseDouble (contWeightTxtField.getText ());
        Double perc3 = Double.parseDouble (assWeightTxtField.getText ());
        Double total = perc1 + perc2 + perc3;
        if (total != 1)
        {
            JOptionPane.showMessageDialog(calcPnl,
            "Please make sure you inputted correct weights. They must equal 1 together.");
            
        }
    }
    
    private void multiSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiSubjectBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiSubjectBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        
        semTestMarkTxtField.setText ("");
        contAssesTxtField.setText ("");
        assignmentMarkTxtField.setText ("");
        semWeightTxtField.setText ("0.2");
        contWeightTxtField.setText ("0.2");
        assWeightTxtField.setText ("0.6");
        emoticon.setIcon(neutralEmoti);
        passOrFailLbl.setText ("Pass/Fail");
        percentageLbl.setText ("Percentage");
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        calcPnl.setVisible(false);
    }//GEN-LAST:event_helpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPcalcGUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assWeightTxtField;
    private javax.swing.JLabel assignMentMarkLbl;
    private javax.swing.JTextField assignmentMarkTxtField;
    private javax.swing.JLabel assignmentWeightLbl;
    private javax.swing.JPanel calcPnl;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JTextField contAssesTxtField;
    private javax.swing.JLabel contAssesmentWeightLbl;
    private javax.swing.JTextField contWeightTxtField;
    private javax.swing.JLabel emoticon;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton helpBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton multiSubjectBtn;
    private javax.swing.JLabel passOrFailLbl;
    private javax.swing.JLabel percentageLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel semTestMarkLbl;
    private javax.swing.JTextField semTestMarkTxtField;
    private javax.swing.JTextField semWeightTxtField;
    private javax.swing.JLabel semesterTestWeightLbl;
    private javax.swing.JComboBox subjectsCmboBox;
    // End of variables declaration//GEN-END:variables
}
