/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

/**
 *
 * @author Nunes
 */
public class DpCalcGuiFrame extends javax.swing.JFrame {
        Double assignment = 0.0;
        Double semesterTest = 0.0;
        Double continuous = 0.0;
        Double assignmentWeight;
        Double semesterTestWeight;
        Double continousAssessmentWeight;
        String studentName;
        String subject;
        String studentDVnumber;
    /**
     * Creates new form DpCalcGuiFramee
     */
    public DpCalcGuiFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLbl = new javax.swing.JPanel();
        muiltSubBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        calBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        assMarkLbl = new javax.swing.JLabel();
        semMarkLbl = new javax.swing.JLabel();
        conAssMarkLbl = new javax.swing.JLabel();
        assWeightLbl = new javax.swing.JLabel();
        semWeightLbl = new javax.swing.JLabel();
        passFailLbl = new javax.swing.JLabel();
        emoticonLbl = new javax.swing.JLabel();
        contAssWeightLbl = new javax.swing.JLabel();
        semMarkTxtField = new javax.swing.JTextField();
        assWeightTxtField = new javax.swing.JTextField();
        contWeightTxtField = new javax.swing.JTextField();
        assMarkTxtField = new javax.swing.JTextField();
        semTestWeightTxtField = new javax.swing.JTextField();
        contAssMarkTxtField = new javax.swing.JTextField();
        subjectCmbBox = new javax.swing.JComboBox();
        persentageLbl = new javax.swing.JLabel();
        itemTxtField = new javax.swing.JTextField();
        clickBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DP Calculator - by Inocencio Nunes");

        headingLbl.setBorder(new javax.swing.border.MatteBorder(null));
        headingLbl.setName("calculationPanel"); // NOI18N

        muiltSubBtn.setMnemonic('A');
        muiltSubBtn.setText("Add Subjects");
        muiltSubBtn.setToolTipText("Press here to make my life harder");
        muiltSubBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        helpBtn.setMnemonic('H');
        helpBtn.setText("Help");
        helpBtn.setToolTipText("gives helps");
        helpBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resetBtn.setMnemonic('R');
        resetBtn.setText("Reset");
        resetBtn.setToolTipText("put in order");
        resetBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        calBtn.setMnemonic('C');
        calBtn.setText("Calculete");
        calBtn.setToolTipText("Work it out");
        calBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("DP Calculator");

        assMarkLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        assMarkLbl.setText("Assignment Mark:");
        assMarkLbl.setToolTipText("Please enter your assignment  mark");

        semMarkLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semMarkLbl.setText("Semester Test Mark:");
        semMarkLbl.setToolTipText("Please enter your semester");

        conAssMarkLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        conAssMarkLbl.setText("Continuous Assessment Mark:");
        conAssMarkLbl.setToolTipText("Please enter your continuous assessment mark");

        assWeightLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        assWeightLbl.setText("Assignment Weight");

        semWeightLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        semWeightLbl.setText("Semester Test Weight:");

        passFailLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        passFailLbl.setText("Pass or Fail ");

        emoticonLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nunes\\Work\\C_ITOO121Project\\src\\Sorc\\face.jpeg")); // NOI18N
        emoticonLbl.setText("emoticon");

        contAssWeightLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        contAssWeightLbl.setText("Continuous Assessnment Weight:");

        semMarkTxtField.setToolTipText("please enter your semester mark");

        assWeightTxtField.setText("0.6");
        assWeightTxtField.setToolTipText("Please enter your assignment weight");

        contWeightTxtField.setText("0.2");
        contWeightTxtField.setToolTipText("Please enter your continuous assessment weight");

        assMarkTxtField.setToolTipText("type your assignment mark, number only");

        semTestWeightTxtField.setText("0.2");
        semTestWeightTxtField.setToolTipText("Please enter your semester weight");

        contAssMarkTxtField.setToolTipText("please enter your continuous assessment mark");

        subjectCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Object Oriented Programming", "Human Computer Interaction", "Software Development Project", "Introducation to Information Systems", "Business Communication" }));
        subjectCmbBox.setToolTipText("Please select a subject");
        subjectCmbBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subjectCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCmbBoxActionPerformed(evt);
            }
        });

        persentageLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        persentageLbl.setText("Persentage");

        clickBtn.setText("Click Me");
        clickBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headingLblLayout = new javax.swing.GroupLayout(headingLbl);
        headingLbl.setLayout(headingLblLayout);
        headingLblLayout.setHorizontalGroup(
            headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLblLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingLblLayout.createSequentialGroup()
                        .addComponent(subjectCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headingLblLayout.createSequentialGroup()
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headingLblLayout.createSequentialGroup()
                                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assMarkLbl)
                                    .addComponent(semMarkLbl)
                                    .addComponent(conAssMarkLbl)
                                    .addComponent(assWeightLbl)
                                    .addComponent(semWeightLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contAssMarkTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assWeightTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(semMarkTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assMarkTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(134, 134, 134)
                                .addComponent(emoticonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(headingLblLayout.createSequentialGroup()
                                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(headingLblLayout.createSequentialGroup()
                                            .addComponent(contAssWeightLbl)
                                            .addGap(18, 18, 18)
                                            .addComponent(contWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(headingLblLayout.createSequentialGroup()
                                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(calBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clickBtn)
                                            .addGroup(headingLblLayout.createSequentialGroup()
                                                .addComponent(muiltSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
            .addGroup(headingLblLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headingLblLayout.createSequentialGroup()
                            .addComponent(passFailLbl)
                            .addGap(167, 167, 167)
                            .addComponent(persentageLbl)
                            .addGap(129, 129, 129)))
                    .addComponent(itemTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headingLblLayout.setVerticalGroup(
            headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headingLblLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(emoticonLbl)
                        .addGap(215, 215, 215))
                    .addGroup(headingLblLayout.createSequentialGroup()
                        .addComponent(subjectCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assMarkLbl)
                            .addComponent(assMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semMarkLbl)
                            .addComponent(semMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conAssMarkLbl)
                            .addComponent(contAssMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assWeightLbl)
                            .addComponent(assWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semWeightLbl))
                        .addGap(18, 18, 18)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contAssWeightLbl)
                            .addComponent(contWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(muiltSubBtn)
                            .addComponent(helpBtn)
                            .addComponent(resetBtn)
                            .addComponent(calBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headingLblLayout.createSequentialGroup()
                                .addComponent(itemTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(headingLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(persentageLbl)
                                    .addComponent(passFailLbl)))
                            .addComponent(clickBtn))
                        .addGap(61, 61, 61))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        headingLbl.getAccessibleContext().setAccessibleName("DPcalculator");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        assMarkTxtField.setText("");
        semMarkTxtField.setText("");
        contAssMarkTxtField.setText(""); 
        assWeightTxtField.setText("0.6");
        semTestWeightTxtField.setText("0.2");
        contWeightTxtField.setText("0.2");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void calBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calBtnActionPerformed
        this.assignment = Double.parseDouble(assMarkTxtField.getText());
        this.semesterTest = Double.parseDouble(semMarkTxtField.getText());
        this.continuous = Double.parseDouble(contAssMarkTxtField.getText());
        
        this.assignmentWeight = Double.parseDouble(assWeightTxtField.getText());
        this.semesterTestWeight = Double.parseDouble(semTestWeightTxtField.getText());
        this.continousAssessmentWeight = Double.parseDouble(contWeightTxtField.getText());
        
        //DPcalc calculator = new DPcalc(testAss, testSem, testCont);
        DPcalc calculator = new DPcalc(assignment, semesterTest, continuous, studentName, subject, studentDVnumber, assignmentWeight, semesterTestWeight, continousAssessmentWeight);
        Double testResult1 = calculator.calculateDP();
        persentageLbl.setText(String.valueOf(testResult1+"%"));
        
        if (testResult1 > 40){
            passFailLbl.setText("Pass");
        }
        else{
            passFailLbl.setText("Fail");
        }
    }//GEN-LAST:event_calBtnActionPerformed

    private void clickBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnActionPerformed
        
    }//GEN-LAST:event_clickBtnActionPerformed

    private void subjectCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCmbBoxActionPerformed
        itemTxtField.setText(subjectCmbBox.getSelectedItem().toString());
        String sub = itemTxtField.getText();
        if ("Object Oriented Programming".equals(sub)){
            System.out.println("yes");
            //itemTxtField.setText("5000");
        }
        else{
            System.out.println("no");
        }
    }//GEN-LAST:event_subjectCmbBoxActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assMarkLbl;
    private javax.swing.JTextField assMarkTxtField;
    private javax.swing.JLabel assWeightLbl;
    private javax.swing.JTextField assWeightTxtField;
    private javax.swing.JButton calBtn;
    private javax.swing.JButton clickBtn;
    private javax.swing.JLabel conAssMarkLbl;
    private javax.swing.JTextField contAssMarkTxtField;
    private javax.swing.JLabel contAssWeightLbl;
    private javax.swing.JTextField contWeightTxtField;
    private javax.swing.JLabel emoticonLbl;
    private javax.swing.JPanel headingLbl;
    private javax.swing.JButton helpBtn;
    private javax.swing.JTextField itemTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton muiltSubBtn;
    private javax.swing.JLabel passFailLbl;
    private javax.swing.JLabel persentageLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel semMarkLbl;
    private javax.swing.JTextField semMarkTxtField;
    private javax.swing.JTextField semTestWeightTxtField;
    private javax.swing.JLabel semWeightLbl;
    private javax.swing.JComboBox subjectCmbBox;
    // End of variables declaration//GEN-END:variables
}
