/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

/**
 *
 * @author Barend Van Der Berg DV2015-0020
 */
public class DPcalcGUIframe extends javax.swing.JFrame {

    /**
     * Creates new form DPcalcGUIframe
     */
    public DPcalcGUIframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcPNL = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        semMarkLbl = new javax.swing.JLabel();
        contAssMarkLbl = new javax.swing.JLabel();
        assMarkLbl = new javax.swing.JLabel();
        semTestWeight = new javax.swing.JLabel();
        contAssWeight = new javax.swing.JLabel();
        assWeight = new javax.swing.JLabel();
        pressCalc = new javax.swing.JLabel();
        persLbl = new javax.swing.JLabel();
        emoticon = new javax.swing.JLabel();
        subjectCmboBox = new javax.swing.JComboBox();
        semTestMarktxtFld = new javax.swing.JTextField();
        contAssMarktxtFld = new javax.swing.JTextField();
        assMArktextFld = new javax.swing.JTextField();
        semTestWeighttxtFld = new javax.swing.JTextField();
        contAssWeighttxtFld = new javax.swing.JTextField();
        assWeighttxtFld = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        addSubjectBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DP Calculator - by Barend Van Der Berg");

        headingLbl.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        headingLbl.setText("DP Calculator");

        semMarkLbl.setText("Semester Test Mark:");

        contAssMarkLbl.setText("Continuous Assessment Mark:");

        assMarkLbl.setText("Assignment Mark:");

        semTestWeight.setText("Semester Test Weight:");

        contAssWeight.setText("Continuous Assessment Weight:");

        assWeight.setText("Assignment Weight:");

        pressCalc.setText("Press Calculate to calculate DP.");

        persLbl.setText("Precentage Achieved");

        emoticon.setText("emoticon");

        subjectCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Subject", "Introduction to Information Systems", "Human Computer Interaction", "Networking Technologies", "Computer skills development", "Object Orientated Programmming" }));

        contAssMarktxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contAssMarktxtFldActionPerformed(evt);
            }
        });

        semTestWeighttxtFld.setText("0.2");

        contAssWeighttxtFld.setText("0.2");
        contAssWeighttxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contAssWeighttxtFldActionPerformed(evt);
            }
        });

        assWeighttxtFld.setText("0.6");

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        addSubjectBtn.setText("Add Subject");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Help");

        javax.swing.GroupLayout calcPNLLayout = new javax.swing.GroupLayout(calcPNL);
        calcPNL.setLayout(calcPNLLayout);
        calcPNLLayout.setHorizontalGroup(
            calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPNLLayout.createSequentialGroup()
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(calcPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(calcPNLLayout.createSequentialGroup()
                        .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(calcPNLLayout.createSequentialGroup()
                                    .addGap(185, 185, 185)
                                    .addComponent(headingLbl))
                                .addGroup(calcPNLLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(calcPNLLayout.createSequentialGroup()
                                            .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(contAssMarkLbl)
                                                .addComponent(semMarkLbl)
                                                .addComponent(contAssWeight)
                                                .addComponent(assMarkLbl)
                                                .addComponent(semTestWeight)
                                                .addComponent(assWeight)
                                                .addComponent(emoticon))
                                            .addGap(21, 21, 21)
                                            .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(semTestWeighttxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(contAssWeighttxtFld)
                                                .addComponent(assWeighttxtFld)
                                                .addComponent(semTestMarktxtFld)
                                                .addComponent(contAssMarktxtFld)
                                                .addComponent(assMArktextFld)))
                                        .addGroup(calcPNLLayout.createSequentialGroup()
                                            .addGap(176, 176, 176)
                                            .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(persLbl)
                                                .addComponent(pressCalc)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(resetBtn))
                    .addGroup(calcPNLLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addSubjectBtn)
                            .addComponent(calculateBtn))))
                .addGap(63, 63, 63))
        );
        calcPNLLayout.setVerticalGroup(
            calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPNLLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(headingLbl)
                .addGap(18, 18, 18)
                .addComponent(subjectCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semMarkLbl)
                    .addComponent(semTestMarktxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contAssMarkLbl)
                    .addComponent(contAssMarktxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assMarkLbl)
                    .addComponent(assMArktextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semTestWeight)
                    .addComponent(semTestWeighttxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contAssWeight)
                    .addComponent(contAssWeighttxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assWeight)
                    .addComponent(assWeighttxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pressCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateBtn)
                    .addComponent(persLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSubjectBtn)
                    .addComponent(emoticon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calcPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contAssMarktxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contAssMarktxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contAssMarktxtFldActionPerformed

    private void contAssWeighttxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contAssWeighttxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contAssWeighttxtFldActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        semTestMarktxtFld.setText("");
        assMArktextFld.setText("");
        semTestWeight.setText("0.2");
        subjectCmboBox.setSelectedIndex(0);
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPcalcGUIframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JTextField assMArktextFld;
    private javax.swing.JLabel assMarkLbl;
    private javax.swing.JLabel assWeight;
    private javax.swing.JTextField assWeighttxtFld;
    private javax.swing.JPanel calcPNL;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel contAssMarkLbl;
    private javax.swing.JTextField contAssMarktxtFld;
    private javax.swing.JLabel contAssWeight;
    private javax.swing.JTextField contAssWeighttxtFld;
    private javax.swing.JLabel emoticon;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel persLbl;
    private javax.swing.JLabel pressCalc;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel semMarkLbl;
    private javax.swing.JTextField semTestMarktxtFld;
    private javax.swing.JLabel semTestWeight;
    private javax.swing.JTextField semTestWeighttxtFld;
    private javax.swing.JComboBox subjectCmboBox;
    // End of variables declaration//GEN-END:variables
}
