/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dominic
 */
public class DPCalcGuiFrame extends javax.swing.JFrame {

    /**
     * Creates new form DPCalcGuiFrame
     */
    public DPCalcGuiFrame() {
        initComponents();
        this.setVisible(true);
    }
// This is used to locate the images i used and it gives them the appropriat evariable names
    ImageIcon frownIcon = new ImageIcon("src\\main\\resources\\sadSmiley.jpg"," ");
    ImageIcon neutralIcon = new ImageIcon ("src\\main\\resources\\NeutralFace.jpg"," ");
    ImageIcon smileIcon = new ImageIcon ("src\\main\\resources\\HappySmiley.gif", " ");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CalcPanel = new javax.swing.JPanel();
        HeadingLbl = new javax.swing.JLabel();
        semMarkLbl = new javax.swing.JLabel();
        contAssMarkLbl = new javax.swing.JLabel();
        assMarkLbl = new javax.swing.JLabel();
        semTestWeightLbl = new javax.swing.JLabel();
        contAssWeightLbl = new javax.swing.JLabel();
        assWeightLbl = new javax.swing.JLabel();
        passFailLbl = new javax.swing.JLabel();
        persLbl = new javax.swing.JLabel();
        emoticon = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox();
        semTestMarkTxtField = new javax.swing.JTextField();
        contAssMarkTxtField = new javax.swing.JTextField();
        assMarkTxtField = new javax.swing.JTextField();
        semTestWeightTxtField = new javax.swing.JTextField();
        contAssWeightTxtField = new javax.swing.JTextField();
        assWeightTxtField = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        addSubjectBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DP Calculator - Dominic Carvalho");

        HeadingLbl.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        HeadingLbl.setText("DP Calculator");

        semMarkLbl.setText("Semester Test Mark");

        contAssMarkLbl.setText("Continuous Assesment Mark");

        assMarkLbl.setText("Assignment Mark");

        semTestWeightLbl.setText("Semester Test Weight ");

        contAssWeightLbl.setText("Continuous Assesment Weight");

        assWeightLbl.setText("Assignment Weight");

        passFailLbl.setText("pass/fail");

        persLbl.setText("Percentage :");

        emoticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NeutralFace.jpg"))); // NOI18N

        subjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Object Orientated Programming", "Introduction to Information Systems", "Human Computer Interaction", "Networking Technologies", "Computer Skills", "Software Development Project" }));

        assMarkTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assMarkTxtFieldActionPerformed(evt);
            }
        });

        semTestWeightTxtField.setText("0.2");
        semTestWeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semTestWeightTxtFieldActionPerformed(evt);
            }
        });

        contAssWeightTxtField.setText("0.2");
        contAssWeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contAssWeightTxtFieldActionPerformed(evt);
            }
        });

        assWeightTxtField.setText("0.6");
        assWeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assWeightTxtFieldActionPerformed(evt);
            }
        });

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        addSubjectBtn.setText("Add Subject");

        javax.swing.GroupLayout CalcPanelLayout = new javax.swing.GroupLayout(CalcPanel);
        CalcPanel.setLayout(CalcPanelLayout);
        CalcPanelLayout.setHorizontalGroup(
            CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcPanelLayout.createSequentialGroup()
                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contAssWeightLbl)
                            .addComponent(semTestWeightLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contAssWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persLbl)
                            .addComponent(passFailLbl)))
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalcPanelLayout.createSequentialGroup()
                                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(CalcPanelLayout.createSequentialGroup()
                                        .addComponent(assMarkLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(assMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CalcPanelLayout.createSequentialGroup()
                                        .addComponent(semMarkLbl)
                                        .addGap(58, 58, 58)
                                        .addComponent(semTestMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CalcPanelLayout.createSequentialGroup()
                                        .addComponent(contAssMarkLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(contAssMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CalcPanelLayout.createSequentialGroup()
                                        .addComponent(resetBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(helpBtn))
                                    .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalcPanelLayout.createSequentialGroup()
                                .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(assWeightLbl)))
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(HeadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(emoticon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CalcPanelLayout.setVerticalGroup(
            CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcPanelLayout.createSequentialGroup()
                .addComponent(HeadingLbl)
                .addGap(33, 33, 33)
                .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semMarkLbl)
                            .addComponent(semTestMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contAssMarkLbl)
                            .addComponent(contAssMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assMarkLbl)
                            .addComponent(assMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(assWeightLbl))
                    .addGroup(CalcPanelLayout.createSequentialGroup()
                        .addComponent(calculateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn)
                            .addComponent(helpBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSubjectBtn)
                            .addComponent(assWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semTestWeightLbl)
                    .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passFailLbl)
                        .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persLbl)
                    .addGroup(CalcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contAssWeightLbl)
                        .addComponent(contAssWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emoticon)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assMarkTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assMarkTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assMarkTxtFieldActionPerformed

    private void semTestWeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semTestWeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semTestWeightTxtFieldActionPerformed

    private void contAssWeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contAssWeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contAssWeightTxtFieldActionPerformed

    private void assWeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assWeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assWeightTxtFieldActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
//we have not incorperated the string name and dv number into our code so it is set to ""
        //The combo box is used to get the the different subjects
String name = "";
String dv = "";
String subject = subjectComboBox.getSelectedItem().toString();
    
   //This is sed to make sure that the weights are always equal to one or a message will show up when trying to calculate the dp
    Double percentage1 = Double.parseDouble(assWeightTxtField.getText());
    Double percentage2 = Double.parseDouble(semTestWeightTxtField.getText());
    Double percentage3 = Double.parseDouble( contAssWeightTxtField.getText());
    Double total = percentage1+percentage2+percentage3;
    if (total !=1){
        
        JOptionPane.showMessageDialog(CalcPanel,"The total number of weights may not excced 1 when added together");
    }
    
    
   

    DPcalc calc = new DPcalc (Double.parseDouble(assMarkTxtField.getText()),Double.parseDouble(semTestMarkTxtField.getText()), Double.parseDouble(contAssMarkTxtField.getText()),name,dv,subject, Double.parseDouble(assWeightTxtField.getText()),Double.parseDouble(semTestWeightTxtField.getText()), Double.parseDouble(contAssWeightTxtField.getText()));
    persLbl.setText("Percentage : "+calc.calculateDP()+"");
    if(calc.canWriteExams()==true){
                passFailLbl.setText("Pass");
                emoticon.setIcon(smileIcon);
    }
    else
    {
        passFailLbl.setText("Fail");
        emoticon.setIcon(frownIcon);
    }
 
 
// TODO add your handling code here:
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
//when the reset button is pushed it returns all fields to its intended state
semTestMarkTxtField.setText(""); 
contAssMarkTxtField.setText("");
assMarkTxtField.setText("");
semTestWeightTxtField.setText("0.2");
contAssWeightTxtField.setText("0.2");
assWeightTxtField.setText("0.6");
persLbl.setText("Percentage :");
emoticon.setIcon(neutralIcon);
// Assigning a blank space to the mark fields and assigning the weights to the weight fields when pressing the reset button
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPCalcGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPCalcGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPCalcGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPCalcGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPCalcGuiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalcPanel;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JLabel assMarkLbl;
    private javax.swing.JTextField assMarkTxtField;
    private javax.swing.JLabel assWeightLbl;
    private javax.swing.JTextField assWeightTxtField;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel contAssMarkLbl;
    private javax.swing.JTextField contAssMarkTxtField;
    private javax.swing.JLabel contAssWeightLbl;
    private javax.swing.JTextField contAssWeightTxtField;
    private javax.swing.JLabel emoticon;
    private javax.swing.JButton helpBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passFailLbl;
    private javax.swing.JLabel persLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel semMarkLbl;
    private javax.swing.JTextField semTestMarkTxtField;
    private javax.swing.JLabel semTestWeightLbl;
    private javax.swing.JTextField semTestWeightTxtField;
    private javax.swing.JComboBox subjectComboBox;
    // End of variables declaration//GEN-END:variables
}
