/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.pearson.cti.studentdpcalculator;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author noelp
 */
public class DPcalcGUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form DPcalcGUIFrame
     */
    public DPcalcGUIFrame() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcPnl = new javax.swing.JPanel();
        DPcalcLbl = new javax.swing.JLabel();
        semTestMarkLbl = new javax.swing.JLabel();
        contMarkLbl = new javax.swing.JLabel();
        assMarkLbl = new javax.swing.JLabel();
        semTestWeightLbl = new javax.swing.JLabel();
        contWeightLbl = new javax.swing.JLabel();
        assWeightLbl = new javax.swing.JLabel();
        passFailLbl = new javax.swing.JLabel();
        perLbl = new javax.swing.JLabel();
        emoticonLbl = new javax.swing.JLabel();
        subjectCmboBox = new javax.swing.JComboBox();
        semTestMarkTxtField = new javax.swing.JTextField();
        contMarkTxtField = new javax.swing.JTextField();
        assMarkTxtField = new javax.swing.JTextField();
        semTestWeightTxtField = new javax.swing.JTextField();
        contWeigtTxtField = new javax.swing.JTextField();
        assWeightTxtField = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        calcBtn = new javax.swing.JButton();
        multiSubjectBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DP calculator - by Timothy Pietersen");

        DPcalcLbl.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        DPcalcLbl.setText("DP Calculator");

        semTestMarkLbl.setText("Semester Test Mark:");

        contMarkLbl.setText("Continuous Assessment Mark:");

        assMarkLbl.setText("Assignment Mark:");

        semTestWeightLbl.setText("Semester Test Weight:");

        contWeightLbl.setText("Continuous Assessment Weight");

        assWeightLbl.setText("Assignment Weight:");

        passFailLbl.setText("Press Calculate to calculate DP");

        perLbl.setText("Percentage achieved");

        emoticonLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutral.jpg"))); // NOI18N

        subjectCmboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Networking Technologies", "Introductionto Information Systems", "Human Computer Interaction", "Object Oriented Programming", "Computer Skills Development" }));

        semTestMarkTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semTestMarkTxtFieldActionPerformed(evt);
            }
        });

        assMarkTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assMarkTxtFieldActionPerformed(evt);
            }
        });

        semTestWeightTxtField.setText("0.2");

        contWeigtTxtField.setText("0.2");

        assWeightTxtField.setText("0.6");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        calcBtn.setText("Calculate");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        multiSubjectBtn.setText("Add Subject");

        helpBtn.setText("Help");

        javax.swing.GroupLayout calcPnlLayout = new javax.swing.GroupLayout(calcPnl);
        calcPnl.setLayout(calcPnlLayout);
        calcPnlLayout.setHorizontalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DPcalcLbl)
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semTestMarkLbl)
                    .addComponent(contMarkLbl)
                    .addComponent(assMarkLbl)
                    .addComponent(semTestWeightLbl)
                    .addComponent(contWeightLbl)
                    .addComponent(assWeightLbl)
                    .addComponent(passFailLbl)
                    .addComponent(emoticonLbl))
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(semTestMarkTxtField)
                                .addComponent(contMarkTxtField)
                                .addComponent(assMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calcPnlLayout.createSequentialGroup()
                                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(assWeightTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contWeigtTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(perLbl))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetBtn)
                            .addComponent(calcBtn))
                        .addGap(18, 18, 18)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multiSubjectBtn)
                            .addComponent(helpBtn))))
                .addGap(27, 27, 27))
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(subjectCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcPnlLayout.setVerticalGroup(
            calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(DPcalcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semTestMarkLbl)
                    .addComponent(semTestMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contMarkLbl)
                    .addComponent(contMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assMarkLbl)
                    .addComponent(assMarkTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semTestWeightLbl)
                    .addComponent(semTestWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contWeightLbl)
                    .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contWeigtTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(perLbl)))
                .addGap(18, 18, 18)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assWeightLbl)
                    .addComponent(assWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPnlLayout.createSequentialGroup()
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcBtn)
                            .addComponent(multiSubjectBtn))
                        .addGap(18, 18, 18)
                        .addGroup(calcPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn)
                            .addComponent(helpBtn)))
                    .addComponent(passFailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emoticonLbl)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calcPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        Double assignmentMark = Double.parseDouble(assMarkTxtField.getText());
        Double semesterTestMark = Double.parseDouble(semTestMarkTxtField.getText());
        Double continuousAssessmentMark = Double.parseDouble(contMarkTxtField.getText());
        Double assignmentWeight = Double.parseDouble(assWeightTxtField.getText());
        Double semesterTestWeight = Double.parseDouble(semTestWeightTxtField.getText());
        Double continuousAssessmentWeight = Double.parseDouble(contWeigtTxtField.getText());
        String studentName = "";
        String studentDVnumber ="";

        if(assignmentMark <= 100.0 &&
            semesterTestMark <= 100.0 &&
            continuousAssessmentMark <= 100.0 &&
            assignmentMark >= 0.0 &&
            semesterTestMark >= 0.0 &&
            continuousAssessmentMark >= 0.0 &&
            assignmentWeight <= 1.0 &&
            semesterTestWeight <= 1.0 &&
            continuousAssessmentWeight <= 1.0 &&
            assignmentWeight >= 0.0 &&
            semesterTestWeight >= 0.0 &&
            continuousAssessmentWeight >= 0.0){
        }

        if ((assignmentWeight + semesterTestWeight + continuousAssessmentWeight) == 1.0){
            DPcalc calc = new DPcalc(assignmentMark,
                semesterTestMark,
                continuousAssessmentMark,
                studentName, 
                studentDVnumber,
                subjectCmboBox.getSelectedItem().toString(),
                assignmentWeight,
                semesterTestWeight,
                continuousAssessmentWeight);
            if (calc.canWriteExams()){
                passFailLbl.setText("Pass");
                try {
                    emoticonLbl.setIcon( new ImageIcon(ImageIO.read(this.getClass().getClassLoader().getResource("happy.jpg"))));
                } catch (IOException ex) {
                    Logger.getLogger(DPcalcGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                passFailLbl.setText("Fail");
                try {
                    emoticonLbl.setIcon( new ImageIcon(ImageIO.read(this.getClass().getClassLoader().getResource("sad.jpg"))));
                } catch (IOException ex) {
                    Logger.getLogger(DPcalcGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            perLbl.setText("Percentage Achieved: " + calc.calculateDP() + "%");
            }
            
        }
        //perTxtField.setText((semMark * semTestMarkTxtField) + (contMark * contMarkTxtField) + (assMark * assMarkTxtField)) +"";        // TODO add your handling code here:
    }//GEN-LAST:event_calcBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed

        semTestMarkTxtField.setText("") ;
        contMarkTxtField.setText("") ;
        assMarkTxtField.setText("") ;
        semTestWeightTxtField.setText("0.2") ;
        contWeigtTxtField.setText("0.2") ;
        assWeightTxtField.setText("0.6") ;
        passFailLbl.setText("Pass/Fail");
        perLbl.setText("Percentage Achieved: ");
        try {
            emoticonLbl.setIcon( new ImageIcon(ImageIO.read(this.getClass().getClassLoader().getResource("neutral.jpg"))));
        } catch (IOException ex) {
            Logger.getLogger(DPcalcGUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        subjectCmboBox.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed

    private void semTestMarkTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semTestMarkTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semTestMarkTxtFieldActionPerformed

    private void assMarkTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assMarkTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assMarkTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPcalcGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPcalcGUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DPcalcLbl;
    private javax.swing.JLabel assMarkLbl;
    private javax.swing.JTextField assMarkTxtField;
    private javax.swing.JLabel assWeightLbl;
    private javax.swing.JTextField assWeightTxtField;
    private javax.swing.JButton calcBtn;
    private javax.swing.JPanel calcPnl;
    private javax.swing.JLabel contMarkLbl;
    private javax.swing.JTextField contMarkTxtField;
    private javax.swing.JLabel contWeightLbl;
    private javax.swing.JTextField contWeigtTxtField;
    private javax.swing.JLabel emoticonLbl;
    private javax.swing.JButton helpBtn;
    private javax.swing.JButton multiSubjectBtn;
    private javax.swing.JLabel passFailLbl;
    private javax.swing.JLabel perLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel semTestMarkLbl;
    private javax.swing.JTextField semTestMarkTxtField;
    private javax.swing.JLabel semTestWeightLbl;
    private javax.swing.JTextField semTestWeightTxtField;
    private javax.swing.JComboBox subjectCmboBox;
    // End of variables declaration//GEN-END:variables
}
